<div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?></h3>
                <a href="<?php echo $this->getUrl('user/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->htmlEscape($this->getUser()->getName()) ?><br />
                    <?php echo $this->htmlEscape($this->getUser()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Extra Something') ?></h3>
                <a href="<?php echo $this->getUrl('*/*/*') ?>"><?php echo $this->__('Extra Edit') ?></a>
            </div>
            <div class="box-content">
                <p>Some more stuff can be put here </p>
            </div>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('user.account.dashboard.info.extra')?>
    </div>
</div>
